version: "3.9"
services:
  wordpress:
    build: ./wp/conf
    ports: 
      - "8080:80"
    restart: always
    volumes: 
        - "${PWD}/wp/conf/default:/etc/nginx/sites-available/default"
        - "${PWD}/wp/:/var/www/html/"
    env_file:
      - .env
    depends_on:
      - db
      - adminer
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes: 
        - "${PWD}/wp/conf/mysql/:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 4043:8080